language: node_js
node_js:
    - "0.12"

before_install:
    - npm install -g hexo


before_script:
    - git config --global user.name 'extracc'
    - git config --global user.email 'ab_z@qq.com'

script:
    - hexo g

after_success:
    - mkdir .deploy
    - cd .deploy
    - git init
    - git remote add origin $DEPLOY_REPO
    - cp -r ../public/* .
    - git add -A .
    - git commit -m 'Site updated'
    - git push --force --quiet origin master
